export const FriendsProfileData = [
  {
    name: 'John',
    accountName: 'Reacto',
    profileImage: require('../../assets/images/profile4.jpeg'),
    posts: 30,
    followers: 31,
    following: 44,
    follow: false,
  },
  {
    name: 'Alice',
    accountName: 'Javamaster',
    profileImage: require('../../assets/images/profile5.jpeg'),
    posts: 24,
    followers: 120,
    following: 600,
    follow: false,
  },
  {
    name: 'Michael',
    accountName: 'Vuewizard',
    profileImage: require('../../assets/images/profile2.jpeg'),
    posts: 21,
    followers: 7886,
    following: 32,
    follow: false,
  },
  {
    name: 'David',
    accountName: 'Angularking',
    profileImage: require('../../assets/images/post1.jpeg'),
    posts: 123,
    followers: 6425,
    following: 32,
    follow: false,
  },
  {
    name: 'Sarah',
    accountName: 'Svelty',
    profileImage: require('../../assets/images/post2.jpeg'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
  {
    name: 'Daniel',
    accountName: 'Golover',
    profileImage: require('../../assets/images/post3.jpeg'),
    posts: 452,
    followers: '564k',
    following: 31,
    follow: false,
  },
  {
    name: 'Olivia',
    accountName: 'NextJSdev',
    profileImage: require('../../assets/images/post4.jpeg'),
    posts: 543,
    followers: '435k',
    following: 22,
    follow: false,
  },
  {
    name: 'Emily',
    accountName: 'Expressqueen',
    profileImage: require('../../assets/images/post5.jpeg'),
    posts: 234,
    followers: '763k',
    following: 332,
    follow: false,
  },
  {
    name: 'James',
    accountName: 'Javamaster',
    profileImage: require('../../assets/images/post6.jpeg'),
    posts: 111,
    followers: 11223,
    following: 1,
    follow: false,
  },
  {
    name: 'Andrew',
    accountName: 'Denoplayer',
    profileImage: require('../../assets/images/post7.jpeg'),
    posts: 121,
    followers: 43213,
    following: 21,
    follow: false,
  },
  {
    name: 'Sophia',
    accountName: 'NodeNinja',
    profileImage: require('../../assets/images/post8.jpeg'),
    posts: 432,
    followers: '987k',
    following: 24,
    follow: false,
  },
  {
    name: 'Jacob',
    accountName: 'Pythonista',
    profileImage: require('../../assets/images/post9.jpeg'),
    posts: '1.2k',
    followers: '1.2M',
    following: 12,
    follow: false,
  },
  {
    name: 'Mia',
    accountName: 'JQuerylover',
    profileImage: require('../../assets/images/post10.jpeg'),
    posts: 533,
    followers: 64322,
    following: 123,
    follow: false,
  },
];
